dataset: AnimalPose.data.AllAnimals_Sequence_Train
validation_dataset: AnimalPose.data.AllAnimals_Sequence_Validation
animals: ["horse", "sheep", "cat", "dog", "sheep"]#, "tiger"] #TODO: TIGDOG horses are not inside!
image_type: "none" # "mask" "white" "none"
cropped: True # uses cropped_meta dataset uncomment for previous dataset
