dataset: AnimalPose.data.AllAnimalsVOC2011_Train
validation_dataset: AnimalPose.data.AllAnimalsVOC2011_Validation
animals: ["horse", "cat", "tiger", "hellenic_hound", "domestic_sheep"]
synthetic: True # Placeholder, just important for the dataloader
image_type: "white" # "mask" "white" "none"
n_classes: 20
n_channels: 3 # rgb or grayscale
bilinear: true
resize_to: 128
as_grey: False
sigma: 2 # Good way sigma = size/64 for heatmaps
crop: False
augmentation: False
train_size: 0.8
random_state: 42
pck_alpha: 0.5
pck_multi: False
sequence_step_size: 1 # Steps to be taken from one frame to another