dataset: AnimalPose.data.AllAnimals_Sequence_Train
validation_dataset: AnimalPose.data.AllAnimals_Sequence_Validation
animals: ["cat", "dog", "sheep", "horse"]#, "tiger"] #TODO: TIGDOG horses are not inside!