dataset: AnimalPose.data.AllAnimalsVOC2011_Train
validation_dataset: AnimalPose.data.AllAnimalsVOC2011_Validation
#animals: ["cat"]#, "dog"]
#animals: ["sheep", "horse", "cow"]
animals: ["cat", "dog", "sheep", "horse", "cow"]
