n_classes: 20
n_channels: 3 # rgb or grayscale
bilinear: true
resize_to: 128,128
as_grey: False
sigma: 3 # Good way sigma = size/64 for heatmaps
crop: False
augmentation: True
train_size: 0.7
random_state: 42