n_classes: 20
n_channels: 3 # rgb or grayscale
bilinear: true
resize_to: 128
as_grey: False
sigma: 2 # Good way sigma = size/64 for heatmaps
crop: True
augmentation: True
train_size: 0.3
random_state: 42
pck_alpha: 0.5
pck_multi: True
