dataset: AnimalPose.data.Human36MFramesFlow_Train
validation_dataset: AnimalPose.data.Human36MFramesFlow_Validation

dataroot: '/export/scratch/hperrot/Datasets/human3.6M'
flow_calc_mode: 'flownet2'
reverse_flow_input: False
base_frame_step: 10
target_frame_step: 1
calc_size: 1024
load_size: 256
max_dataset_size: .inf
dataset_split_type: 'action'
# dataset_split_type: 'none'
