dataset: AnimalPose.data.AnimalVOC2011_UNet_Train
validation_dataset: AnimalPose.data.AnimalVOC2011_UNet_Validation
dataroot: 'VOC2011/sheeps_meta'
n_classes: 20
n_channels: 1 # rgb or grayscale
bilinear: true
resize_to: 96, 96
as_grey: True