dataset: AnimalPose.data.SingleCatsUNet_Train
validation_dataset: AnimalPose.data.SingleCatsUNet_Validation
dataroot: '/export/home/ffeldman/Masterarbeit/data'
n_classes: 19
n_channels: 3 # rgb or grayscale
bilinear: true
resize_to: 256,256
as_grey: False
