dataset: AnimalPose.data.SingleCatsUNet_Train
validation_dataset: AnimalPose.data.SingleCatsUNet_Validation
dataroot: '/export/home/ffeldman/Masterarbeit/data'
n_classes: 19 # rgb or grayscale
n_channels: 1
bilinear: true
resize_to: 256, 256
as_grey: True