iterator: AnimalPose.train_resnet_classification.Iterator
model: AnimalPose.models.ResnetTorchVisionClass
batch_size: 32
num_steps: 40001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 2000
#Training methods
pretrained: True
resnet_type: 18 #50,101,152
# Losses
losses:
    CEL: True # Cross entropy loss

# logging
integrations:
  git:
    active: False
  wandb:
    active: true
  tensorboard:
    active: true
