iterator: AnimalPose.train_keypoint_predictor.Iterator
model: AnimalPose.models.Deeplabv3Resnet101_Hub
batch_size: 8
num_steps: 500001
lr: 0.0001
cuda: true  # False -> use GPU
pretrained: True
#Training methods
#pretrained_checkpoint:

# Losses
losses:
    L2: true # TODO
    L2_kpt: true # TODO

# logging
integrations:
  git:
    true
  tensorboard:
    active: true
#  wandb:
#    active: false
#    handlers:
#      - scalars


