iterator: AnimalPose.train_animalnet.Iterator
model: AnimalPose.models.AnimalNet
batch_size: 32 # 32 on quattro
num_steps: 40001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 2000
#Training methods
# Encoder pretrained by torchvision
pretrained: True
load_encoder_pretrained:
    active: False
    path: "load_weights/pretrained_resnet18.ckpt"
load_decoder_pretrained:
    active: False
# Superpixel True loads different decoder
superpixel: True
resnet_type: 18 #18, 50,101,152
encoder_latent_dim: 256 # decoder latent dim is automatically set
encoder_2: False

# True sets the encoder_1 variational
variational:
    active: True
    kl_weight: 0.5
# Losses
losses:
    L2: False
    L2_kpt: False # TODO
    KL: True
    perceptual: False
    perceptual_network: "vgg" # alex, squeeze or vgg
    perceptual_weight: 1.0
    #VGGL1Loss
    vgg: True
    vgg_l1_alpha: 1.0
    vgg_alpha: 1.0

# logging
integrations:
  git:
    active: False
  wandb:
    active: True
  tensorboard:
    active: True

