iterator: AnimalPose.train.Iterator
model: AnimalPose.models.stacked_hourglass.HourglassNet.HourglassNet
batch_size: 8
num_steps: 50001
lr: 0.0001
sigma: 1
cuda: true  # False -> use GPU
ckpt_freq: 300
#Training methods
#pretrained_checkpoint:

# hourglass specific
nstack: 8
inp_dim: 256 # image dim must be same as resize_to
#oup_dim: 16 # is the same as num_joints/num_keypoints/n_classes
#num_parts: 16
#increase: 0 # TODO
#keys': ['imgs'],
#num_eval: 2958, # number of val examples used. entire set is 2958
#train_num_eval: 300

#input_res: 256
#output_res: 64
#max_num_people: 1
#loss': [
#    ['combined_hm_loss', 1],
#],
decay_iters: 100000
decay_lr: 2e-4
#num_workers: 2
#use_data_loader: True

# Losses
losses:
    L2: True
    L2_kpt: False

# logging
integrations:
  git:
    true
  tensorboard:
    active: true
#  wandb:
#    active: false
#    handlers:
#      - scalars


