iterator: AnimalPose.train_keypoint_predictor.Iterator
model: AnimalPose.models.ResPoseNet
batch_size: 16
num_steps: 60001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 30000
#Training methods
pretrained: True
resnet_type: 18 #50,101,152
adjust_learning_rate: False
# Pretraining!
load_self_pretrained_encoder:
  active: True
  #path: "logs/2020-05-20T15-16-53_BL_Triplet_EPS0.07MU0.5_10k/train/checkpoints/model-334000.ckpt"
  path: "logs/2020-05-17T23-07-10_TripletwithreconlossEPS0.4MU0.5lambda100k/train/checkpoints/model-394000.ckpt"
load_self_pretrained_decoder:
  active: False
  #path: "logs/2020-05-20T15-16-53_BL_Triplet_EPS0.07MU0.5_10k/train/checkpoints/model-334000.ckpt"
  path: "logs/2020-05-17T23-07-10_TripletwithreconlossEPS0.4MU0.5lambda100k/train/checkpoints/model-394000.ckpt"
# Encoder is frozen by default
freeze_encoder_for: 999999999 #steps helps to train the decoder in first place


#### BELOW THIS ALL CONFIGS ARE FORE KEYPOINT PREDICTORS THE SAME!
# Heatmap
hm:
  # we consider a keypoint to be a keypoint only above thresh
  thresh: 0.01 # 0.01 is a good choice, removes noise in the heatmaps
# PCK
pck:
  pck_multi: True
  type: "object" # "object" or "image"

# Losses
losses:
  L1: False
  L2: True
  KL: False
  perceptual: True
  perceptual_network: "vgg" # alex, squeeze or vgg
  perceptual_weight: 1.0
  #VGGL1Loss
  vgg: False
  vgg_l1_alpha: 1.0
  vgg_alpha: 1.0
# logging
integrations:
  git:
    active: False
  wandb:
    active: True
  tensorboard:
    active: True
