iterator: AnimalPose.train_keypoint_predictor.Iterator
model: AnimalPose.models.ResnetTorchVisionKeypoints
batch_size: 16
num_steps: 40001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 2000
#Training methods
pretrained: True
resnet_type: 18 #50,101,152
adjust_learning_rate: False
#### BELOW THIS ALL CONFIGS ARE FORE KEYPOINT PREDICTORS THE SAME!
# Heatmap
hm:
  # we consider a keypoint to be a keypoint only above thresh
  thresh: 0.8
# PCK
pck:
    thresh: 0.5
    pck_multi: True
    type: "object" # "object" or "image"
# Losses
losses:
    L1: False
    L2: True
    KL: False
    perceptual: False
    perceptual_network: "vgg" # alex, squeeze or vgg
    perceptual_weight: 1.0
# logging
integrations:
  git:
    active: False
  wandb:
    active: True
  tensorboard:
    active: True
