iterator: AnimalPose.train_keypoint_predictor.Iterator
model: AnimalPose.models.ResnetTorchVisionKeypoints
batch_size: 32
num_steps: 50001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 1000
#Training methods
pretrained: True
adjust_learning_rate: True
resnet_type: 18 #50,101,152

# PCK
pck:
    type: "object" # "object" or "image"
    thresh: 0.5

# Losses
losses:
    L2: True # TODO
    #TODO
    KL: False
    perceptual: False
    perceptual_network: "vgg" # alex, squeeze or vgg
    perceptual_weight: 1.0
# logging
integrations:
  git:
    active: False
  wandb:
    active: true
  tensorboard:
    active: true

