iterator: AnimalPose.train.Iterator
model: AnimalPose.models.UNet_hub
batch_size: 8
num_steps: 50001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 1000
#Training methods
#pretrained_checkpoint:

# Losses
losses:
    L2: True # TODO
    L2_kpt: False # TODO

# logging
integrations:
  git:
    active: true
  tensorboard:
    active: true
#  wandb:
#    active: false
#    handlers:
#      - scalars


