iterator: AnimalPose.train_lord.LordIteratorLatent
model: AnimalPose.models.lord_latent
batch_size: 32
num_steps: 40001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 2000
#Training methods
pretrained: False
resnet_type: 18 #50,101,152
# Losses
base_config = dict(
	content_dim=128,
	class_dim=256,

	content_std=1,
	content_decay=1e-4,

	n_adain_layers=4,
	adain_dim=256,

	perceptual_loss=dict(
		layers=[2, 7, 12, 21, 30]
	),

	train=dict(
		batch_size=128,
		n_epochs=200,

		learning_rate=dict(
			generator=3e-4,
			latent=3e-3,
			min=1e-5
		)
	),

train_encoders=
    batch_size=128,
    n_epochs=200

    learning_rate=
        max=1e-4,
        min=1e-5

# logging
integrations:
  git:
    active: False
  wandb:
    active: true
  tensorboard:
    active: true
