iterator: AnimalPose.train.Iterator
model: AnimalPose.models.ResnetTorchVision
batch_size: 8
num_steps: 50001
lr: 0.0001
cuda: true  # False -> use GPU
ckpt_freq: 300
#Training methods
pretrained: True
resnet_type: 152 #50,101,152
# Losses
losses:
    L2: True # TODO
    L2_kpt: False # TODO

# logging
integrations:
  git:
    active: true
  tensorboard:
    active: true

