model: AnimalPose.models.CycleVAE
iterator: AnimalPose.train_cycle_vae.CycleConsistentVAEIterator
num_classes: 500 # number of appearances
batch_size: 8
num_steps: 50000
class_dim: # dimension of class latent space
style_dim: #dimension of style latent space
# loss function coefficient
# 3 reconstruction coef for 64 dim space
reconstruction_coef: 2.0 # coefficient for reconstruction term
reverse_cycle_coef: 10.0 # coefficient for reverse cycle loss term
kl_divergence_coef:  3.0 # coefficient for KL-Divergence loss term

#parser.add_argument('--cuda', type=bool, default=True, help="run the following code on a GPU")
#parser.add_argument('--image_size', type=int, default=28, help="height and width of the image")
#parser.add_argument('--num_channels', type=int, default=1, help="number of channels in the images")
#parser.add_argument('--initial_learning_rate', type=float, default=0.0001, help="starting learning rate")
